baseURL: http://cwd.dhemery.com/
permalinks:
    posts: /:year/:month/:filename/
languageCode: en-us
title: Conversations with Dale
subtitle: About Software Development
copyright: © 2003–2021 Dale H. Emery
taxonomies:
    tag: tags
