baseURL: https://cwd.dhemery.com/
permalinks:
    posts: /:year/:month/:filename/
languageCode: en-us
title: Conversations with Dale
copyright: © 2003–2021 Dale H. Emery
disableKinds: ["posts"]
taxonomies:
    tag: tags
pygmentsUseClasses: true
markup:
    goldmark:
        renderer:
            unsafe: true
